name: "Terraform Workflow"

on:
  workflow_call:
    inputs:
    working-directory:
      required: false
      type: string
      default: "./terraform"

defaults:
  run:
    shell: bash

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{inputs.working-directory}}

        steps:
        
